"""added status2fa colmn in student, author and user table

Revision ID: 018e8616d328
Revises: c4006381ec04
Create Date: 2025-08-18 20:50:48.679909

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '018e8616d328'
down_revision: Union[str, Sequence[str], None] = 'c4006381ec04'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('authors', sa.Column('status_2fa', sa.String(), nullable=True))
    op.add_column('students', sa.Column('status_2fa', sa.String(), nullable=True))
    op.add_column('users', sa.Column('status_2fa', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'status_2fa')
    op.drop_column('students', 'status_2fa')
    op.drop_column('authors', 'status_2fa')
    # ### end Alembic commands ###
