"""added bool student prop in student

Revision ID: 0a4da5fd9d33
Revises: 4ce36e9b1c71
Create Date: 2025-08-08 23:01:31.453240

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0a4da5fd9d33'
down_revision: Union[str, Sequence[str], None] = '4ce36e9b1c71'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('students', sa.Column('IsStudent', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('students', 'IsStudent')
    # ### end Alembic commands ###
