"""updated studentbook junction table

Revision ID: 5f77d04f74eb
Revises: a244c5c999bd
Create Date: 2025-08-11 20:53:47.621450

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5f77d04f74eb'
down_revision: Union[str, Sequence[str], None] = 'a244c5c999bd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('student_books', sa.Column('AssignedAt', sa.DateTime(), nullable=True))
    op.add_column('student_books', sa.Column('ReturnDate', sa.DateTime(), nullable=True))
    op.add_column('student_books', sa.Column('Status', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('student_books', 'Status')
    op.drop_column('student_books', 'ReturnDate')
    op.drop_column('student_books', 'AssignedAt')
    # ### end Alembic commands ###
