"""added usercreatedat in  user table

Revision ID: 6923e887d5a9
Revises: dbea8d82e5f6
Create Date: 2025-08-15 23:40:02.518773

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6923e887d5a9'
down_revision: Union[str, Sequence[str], None] = 'dbea8d82e5f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('user_created_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'user_created_at')
    # ### end Alembic commands ###
