"""added secret2fa colmn in student and author table

Revision ID: c4006381ec04
Revises: e1d021a60601
Create Date: 2025-08-18 19:11:03.015359

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c4006381ec04'
down_revision: Union[str, Sequence[str], None] = 'e1d021a60601'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('authors', sa.Column('secret_2fa', sa.String(), nullable=True))
    op.add_column('students', sa.Column('secret_2fa', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('students', 'secret_2fa')
    op.drop_column('authors', 'secret_2fa')
    # ### end Alembic commands ###
