"""added secret2fa colmn in user table

Revision ID: e1d021a60601
Revises: 8e2c4c2ce387
Create Date: 2025-08-18 16:10:44.299688

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e1d021a60601'
down_revision: Union[str, Sequence[str], None] = '8e2c4c2ce387'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('secret_2fa', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'secret_2fa')
    # ### end Alembic commands ###
